### ISSUE TITLE
Test failed on OS/2 

### ISSUE THREAD

**Issue by TeLLie** [lbellonda/qxmledit#35] opened 2016-03-20 18:37 UTC
Hi

The test failed for OS/2, i use Qt v4.7.3 and Gcc v4.9.3
I send you the output from the test file.

Totals: 80 passed, 1 failed, 0 skipped
********* Finished testing of TestQXmlEdit *********
If you need more info lemme know...

**Comment by lbellonda** [comment] 2016-03-20 21:52
Hello, can you open the file "test/data/xsd/navigation.xsd" in the project tree into QXmlEdit, open the XSD viewer (button "view as XSD") and post a screenshot?

Just for test, in the file test/testxsdnavigation.cpp, at line 245, can you change 
QTest::qWait(200);
into 
QTest::qWait(1200);

and restart the test?

**Comment by TeLLie** [comment] 2016-03-21 06:30
Hi 

I rerun test
This is what gets diff then before:

F:\qxmledit-master\build>diff -ur test.out run.out21-3
--- test.out    2016-03-16 21:48:04.000000000 +0100
+++ run.out21-3 2016-03-21 07:21:04.000000000 +0100
@@ -145,7 +145,6 @@
 PASS   : TestQXmlEdit::testLengthAttributes()
 PASS   : TestQXmlEdit::testColors()
 PASS   : TestQXmlEdit::testIndent()
-QWARN  : TestQXmlEdit::testContainer() QSqlDatabasePrivate::addDatabase: duplicate connection name 'qxmledit-545653056', old connection removed.
 PASS   : TestQXmlEdit::testContainer()
 QWARN  : TestQXmlEdit::testXsdView() QMetaObject::connectSlotsByName: No matching signal for on_gotoAction_triggered()
 QWARN  : TestQXmlEdit::testXsdView() QMetaObject::connectSlotsByName: No matching signal for on_copyNameAction_triggered()
@@ -204,6 +203,7 @@
 QWARN  : TestQXmlEdit::testXsdView() QGraphicsScene::addItem: item has already been added to this scene
 QWARN  : TestQXmlEdit::testXsdView() QGraphicsScene::addItem: item has already been added to this scene
 PASS   : TestQXmlEdit::testXsdView()
+QWARN  : TestQXmlEdit::testXsdLoad() QSqlDatabasePrivate::addDatabase: duplicate connection name 'qxmledit-538235520', old connection removed.
 PASS   : TestQXmlEdit::testXsdLoad()
 QWARN  : TestQXmlEdit::testXsdValidation() XML does not conform to schema. Validation failed.
 Error: Element {test}aa is not defined in this scope.

**Comment by lbellonda** [comment] 2016-03-23 21:09
Hello, I found the cause in the test itself. The fix will be committed with the next batch.

**Comment by TeLLie** [comment] 2016-03-23 21:10
Hi Luca

Ok thankz
Op 23 mrt. 2016 22:09 schreef "Luca Bellonda" <notifications@github.com>:

**Comment by lbellonda** [comment] 2016-03-23 22:58
Code committed in rev ea6ca862ac7f8633a4b25ef5b9c0e7ed471df441. Let me know if tests are ok

**Comment by lbellonda** [comment] 2016-03-27 19:25
Closing the issue after user confirmation.

**Closed by lbellonda** 2016-03-27 19:25 UTC
Labels: OpSys-OS/2
