### ISSUE TITLE
 error: ‘qInitResources_risorse__init_variable__’ defined but not used [-Werror=unused-variable]

### ISSUE THREAD

**Issue by peppelinux** [lbellonda/qxmledit#52] opened 2018-10-03 08:21 UTC
Ubuntu 16.04 fails to compile

````
In file included from /usr/include/qt4/QtCore/qatomic.h:45:0,
                 from /usr/include/qt4/QtCore/qvariant.h:45,
                 from /usr/include/qt4/QtCore/QVariant:1,
                 from globals/includes/qtincludes.h:30,
                 from globals/includes/xmlEdit.h:77,
                 from precompiled_lib.h:27:
../build/lib/rcc/qrc_risorse.cpp:34634:44: error: ‘qInitResources_risorse__init_variable__’ defined but not used [-Werror=unused-variable]
 Q_CONSTRUCTOR_FUNCTION(QT_MANGLE_NAMESPACE(qInitResources_risorse))
                                            ^
/usr/include/qt4/QtCore/qglobal.h:941:21: note: in definition of macro ‘Q_CONSTRUCTOR_FUNCTION0’
    static const int AFUNC ## __init_variable__ = AFUNC();
                     ^
../build/lib/rcc/qrc_risorse.cpp:34634:1: note: in expansion of macro ‘Q_CONSTRUCTOR_FUNCTION’
 Q_CONSTRUCTOR_FUNCTION(QT_MANGLE_NAMESPACE(qInitResources_risorse))
 ^
../build/lib/rcc/qrc_risorse.cpp:34634:24: note: in expansion of macro ‘QT_MANGLE_NAMESPACE’
 Q_CONSTRUCTOR_FUNCTION(QT_MANGLE_NAMESPACE(qInitResources_risorse))
                        ^
cc1plus: all warnings being treated as errors
Makefile.QXmlEditWidget:10999: set di istruzioni per l'obiettivo "../build/lib/obj/qrc_risorse.o" non riuscito
make[1]: *** [../build/lib/obj/qrc_risorse.o] Errore 1
make[1]: uscita dalla directory "/home/wert/Progs/qxmledit/src"
Makefile:41: set di istruzioni per l'obiettivo "sub-src-QXmlEditWidget-pro-make_default-ordered" non riuscito
make: *** [sub-src-QXmlEditWidget-pro-make_default-ordered] Errore 2


````

**Comment by lbellonda** [comment] 2018-10-03 19:01
Ciao, the error is caused by Qt4 libraries with the version of gcc you are using.

You have two options:
* Use Qt5.
* Remove the compile clause that treats warnings as errors (QMAKE_CXXFLAGS +=-Werror) from the ".pro" files where it is declared.

**Comment by lbellonda** [comment] 2018-10-20 20:08
Hello, may I close this ticket?

**Comment by lbellonda** [comment] 2018-11-17 20:21
Closing this ticket.

**Closed by lbellonda** 2018-11-17 20:21 UTC
